# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.1.8
_src_path: https://github.com/calliecameron/copier-template
author_name: Callie Cameron
copyright_start_year: '2023'
exports_requirements_txt: true
github_repo: calliecameron/writer-bot
max_python_version: '3.14'
min_python_version: '3.14'
project_name: writer-bot
user_has_css: false
user_has_html: false
user_has_javascript: false
user_uses_bats: false
