extends: default

ignore:
  - "/.copier-answers.yml"
  - "/.ast_grep/tests/__snapshots__/*.yml"

rules:
  braces:
    forbid: false
    min-spaces-inside: 0
    max-spaces-inside: 0
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  brackets:
    forbid: false
    min-spaces-inside: 0
    max-spaces-inside: 0
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1 # for compatibility with prettier
  document-start: disable
  line-length: disable
